// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enxgeqbloajlbkgfslod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVueGdlcWJsb2FqbGJrZ2ZzbG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjgwOTYsImV4cCI6MjA1NjYwNDA5Nn0.gzuB97KSAr865alVcnWv3PnQcZ4HOJNNE6L5re4-zMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);